// <auto-generated />
using System;
using FeedAggregator.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FeedAggregator.DAL.Data.Migrations
{
    [DbContext(typeof(FeedAggregatorDbContext))]
    [Migration("20180920151613_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FeedAggregator.DAL.Entities.FeedCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChanellUrl");

                    b.Property<int>("UserCollectionId");

                    b.HasKey("Id");

                    b.HasIndex("UserCollectionId");

                    b.ToTable("FeedCollections");
                });

            modelBuilder.Entity("FeedAggregator.DAL.Entities.FeedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<int>("FeedCollectionId");

                    b.Property<string>("Link");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("FeedCollectionId");

                    b.ToTable("FeedItems");
                });

            modelBuilder.Entity("FeedAggregator.DAL.Entities.UserCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserCollections");
                });

            modelBuilder.Entity("FeedAggregator.DAL.Entities.FeedCollection", b =>
                {
                    b.HasOne("FeedAggregator.DAL.Entities.UserCollection", "UserCollection")
                        .WithMany("FeedCollections")
                        .HasForeignKey("UserCollectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FeedAggregator.DAL.Entities.FeedItem", b =>
                {
                    b.HasOne("FeedAggregator.DAL.Entities.FeedCollection", "FeedCollection")
                        .WithMany("FeedItems")
                        .HasForeignKey("FeedCollectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
